name: flutter_node_js
description: "flutter with node_js"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ICONS
  iconsax: ^0.0.8

  # STATE MANAGEMENT
  get: ^4.6.6

  # OTP FIELDS
  otp_pin_field: ^1.2.2

  # UTILITY
  http: ^1.1.2
  connectivity_plus: ^5.0.2

  # LOCAL STORAGE
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/

  fonts:
    - family: Cal
      fonts:
        - asset: assets/fonts/Cal.otf